# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a74ebc30a0a5bb29aec27f05c7d531a386e8de0b9ed991600cae25ce66afdb0879e05ec43d6906c7338031dfd01878155e70c820c0b2a6db01a6ce8e5442c7c9

test:
  secret_key_base: b3f60991b8d137efafce310e6558666154e78a4993332ac8ab8f1c2d5ce2aa96953b94082f3f15ca77debf7ed8239ca01b8416a98eea553fea1e8c3805b51041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
