#!/bin/sh

bundle exec annotate --exclude tests,fixtures,factories,serializers
for i in engines/*; do
  bundle exec annotate --exclude tests,fixtures,factories,serializers --model-dir $i/app/models/
done

