Rails.application.config.assets.precompile += %w( favicon.ico )
Rails.application.config.assets.precompile += %w( apple-touch-icon-precomposed.png )
Rails.application.config.assets.precompile += %w( wiki/wiki.css )
Rails.application.config.assets.precompile += %w( pack/pack.css )
Rails.application.config.assets.precompile += %w( pack/application.js )
Rails.application.config.assets.precompile += %w( pack/packages/packages.js )
Rails.application.config.assets.precompile += %w( pack/uservers/uservers.js )
