development:
  adapter: postgresql
  encoding: unicode
  database: octoshell_basic_development

test:
  adapter: postgresql
  encoding: unicode
  database: octoshell_basic_test

production:
  adapter: postgresql
  encoding: unicode
  database: octoshell_basic_development
