stateDiagram-v2
  direction LR

  state "TRME новый" as created
  state "TRME доступ одобрен" as approved
  state "TRME подготовлен к завершению" as prepared_to_finish
  state "TRME подготовлен к завершению администратором" as prepared_to_deny
  state "TRME отказано в доступе" as denied
  state "TRME завершён" as finished

  [*] --> created
  created --> approved : approve
  approved --> prepared_to_finish : prepare_to_finish
  approved --> prepared_to_deny : prepare_to_deny
  prepared_to_finish --> finished : finish
  prepared_to_deny --> denied : deny